version: "3.9"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: lab7-web:v1

  redis:
    build:
      context: .
      dockerfile: Dockerfile.db

  web2:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/code
    image: lab7-web:v2
